# Imports

In [117]:
import os
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# Define country and parameters

In [190]:
# Select target country
country = 'Chile'

# Set country-specific parameters: ISO codes and buffer size (in meters)
if country == 'Argentina':
    country_short = 'ARG'   # ISO 3-letter code
    country_code = 'AR'     # ISO 2-letter code
elif country == 'Chile':
    country_short = 'CHL'
    country_code = 'CL'
elif country == 'Colombia':
    country_short = 'COL'
    country_code = 'CO'
# Uncomment the following if Mexico is to be included in the analysis
# elif country == 'Mexico':
#     country_short = 'MEX'
#     country_code = 'MX'

# Set working directory

In [191]:
# Define working directory path
wd = (
#     '/your/path/to/working/directory/'
    '/Users/carmen/Library/CloudStorage/OneDrive-TheUniversityofLiverpool/research/latin-mobility-covid'
)

In [192]:
data_subunit0 = pd.read_csv(
    wd + '/data/outputs/' + country_short + '/baseline/'
    + 'movcell-baseline-imput-mov-dist-with-exo-var-flatten-subunit0.csv'
)

In [193]:
data_censored10 = pd.read_csv(
    wd + '/data/outputs/' + country_short + '/baseline/'
    + 'movcell-baseline-imput-mov-dist-with-exo-var-flatten-censored10.csv'
)

In [194]:
data_standard = pd.read_csv(
    wd + '/data/outputs/' + country_short + '/baseline/'
    + 'movcell-baseline-imput-mov-dist-with-exo-var-flatten-standard.csv'
)

In [195]:
data_raw = pd.read_csv(wd + '/data/outputs/' + country_short + '/baseline/baseline_mov.csv')

In [196]:
data_raw = data_raw[data_raw['0'] != -999]
data_raw = data_raw[data_raw['1'] != -999]
data_raw = data_raw[data_raw['2'] != -999]
data_raw = data_raw[data_raw['3'] != -999]
data_raw = data_raw[data_raw['4'] != -999]
data_raw = data_raw[data_raw['5'] != -999]
data_raw = data_raw[data_raw['6'] != -999]
data_raw = data_raw[data_raw['O'] != data_raw['D']]

In [197]:
data_raw

            O       D     0     1     2     3     4     5     6
0      2432.0  2431.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2      2965.0  2977.0  78.4  81.6  81.5  78.2  79.8  51.2  44.0
4      2988.0  2977.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
5      2988.0  2976.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
6      2987.0  2977.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
...       ...     ...   ...   ...   ...   ...   ...   ...   ...
27884  2595.0  2623.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
28299  3833.0  3836.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
28549  3836.0  3875.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
29549  4265.0  4289.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
30138  3369.0  3351.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[9796 rows x 9 columns]

In [198]:
data_subunit0

,O,D,0,1,2,3,4,5,6
0,2432.0,2431.0,12.183542,12.109425,12.190180,12.182484,12.116381,10.603582,9.976496
1,2965.0,2977.0,78.400000,81.600000,81.500000,78.200000,79.800000,51.200000,44.000000
2,2988.0,2977.0,23.406100,22.989478,23.249639,23.042153,23.073653,20.313713,18.733122
3,2988.0,2976.0,17.031162,16.745117,17.025967,16.839432,16.821019,14.918658,14.019906
4,2987.0,2977.0,17.413091,17.125690,17.247146,17.125315,17.076223,15.157203,13.873429
...,...,...,...,...,...,...,...,...,...
29058,4001.0,4043.0,18.388074,18.148888,18.014853,17.985913,17.909682,15.155779,13.635498
29059,2862.0,2891.0,13.945053,13.700952,13.732852,13.686241,13.676305,12.079778,10.952572
29060,2845.0,2612.0,2.663398,2.616020,2.632265,2.614904,2.622983,2.337133,2.140284
29061,4232.0,3820.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29062,2481.0,2933.0,7.300302,7.208226,7.159444,7.161975,7.156129,6.164378,5.468972

In [199]:
data_censored10

,O,D,0,1,2,3,4,5,6
0,2432.0,2431.0,1.431405,1.359488,1.391141,1.396112,1.391266,1.220927,1.079662
1,2965.0,2977.0,78.400000,81.600000,81.500000,78.200000,79.800000,51.200000,44.000000
2,2988.0,2977.0,2.911889,2.792943,2.843273,2.829406,2.840278,2.631995,2.383587
3,2988.0,2976.0,2.182122,2.071018,2.131719,2.113584,2.118075,1.939266,1.753988
4,2987.0,2977.0,2.102030,1.992768,2.030586,2.021770,2.022445,1.847561,1.609615
...,...,...,...,...,...,...,...,...,...
29058,4001.0,4043.0,2.123704,2.022384,2.027149,2.030880,2.027779,1.746849,1.481241
29059,2862.0,2891.0,1.535879,1.438364,1.461970,1.461686,1.466328,1.306838,1.094448
29060,2845.0,2612.0,0.047456,0.042652,0.044184,0.043839,0.044433,0.037896,0.029861
29061,4232.0,3820.0,0.000759,0.000702,0.000720,0.000713,0.000717,0.000568,0.000439
29062,2481.0,2933.0,0.359901,0.330019,0.331979,0.334235,0.335732,0.270554,0.202301

In [200]:
np.sum(data_subunit0['0'])

598500.7352443842

In [201]:
np.sum(data_censored10['0'])

321406.32415508654

In [202]:
np.sum(data_raw['0'])

292801.6